from django import forms
from .models import Sinistre

class SinistreForm(forms.ModelForm):
    class Meta:
        model = Sinistre
        fields = [
            'date_sinistre', 'lieu_sinistre', 'periode_du', 'periode_au', 
            'numero_police', 
            'intervention',
            'nom_a',
            'adresse_a',
            'phone_a',
            'email_a',
            'marque_a',
            'imma_a',
            'visite_du_a',
            'visite_au_a',
            'usage_a',
            'conducteur_a',
            'adresse_conducteur_a',
            'phone_conducteur_a',
            'profession_conducteur_a',
            'numero_permis',
            'date_delivrance_a',
            'lieu_delivrance_a',
            'categorie_a',
            'dure_a',
            'constat_a',
            'salarie_a',
            'nom_b',
            'adresse_b',
            'phone_b',
            'email_b',
            'marque_b',
            'imma_b',
            'visite_du_b',
            'visite_au_b',
            'usage_b',
            'conducteur_b',
            'adresse_conducteur_b',
            'phone_conducteur_b',
            'profession_conducteur_b',
            'numero_permis_b',
            'date_delivrance_b',
            'lieu_delivrance_b',
            'categorie_b',
            'dure_b',
            'constat_b',
            'salarie_b',
            'circonstance',
            'dommages'
        ]

        widgets = {
                'date_sinistre': forms.DateTimeInput(attrs={
                'class': 'form-control border-0',
                'id': 'date_sinistre',
                'placeholder': 'Date et heure du sinistre',
                'type': 'datetime-local',
                'required': True,
            }),
            'lieu_sinistre': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'lieu_sinistre',
                'placeholder': 'Lieu exact du sinistre',
                'required': True,
            }),
            'periode_du': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'periode_du',
                'placeholder': 'Période garantie accordée du',
                'type': 'date',
                'required': True,
            }),
            'periode_au': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'periode_au',
                'placeholder': 'Période garantie accordée au',
                'type': 'date',
                'required': True,
            }),
            'numero_police': forms.NumberInput(attrs={
                'class': 'form-control border-0',
                'id': 'name',
                'placeholder': 'Numéro de police concerné',
                'min': 10000000,
                'max': 90000000,
                'required': True,
            }),
            'intervention': forms.RadioSelect(choices=Sinistre.INTERVENTION_CHOICES, attrs={
                'class': 'form-check-input',
                'required': True,
            }),
            'nom_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'nom_a',
                'placeholder': 'Nom et Prénoms',
                'required': True,
            }),
            'adresse_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'adresse_a',
                'placeholder': 'Adresse',
                'required': True,
            }),
            'phone_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'phone_a',
                'placeholder': 'Téléphone',
                'required': True,
            }),
            'email_a': forms.EmailInput(attrs={
                'class': 'form-control border-0',
                'id': 'email_a',
                'placeholder': 'Email',
                'required': True,
            }),
            'marque_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'marque_a',
                'placeholder': 'Marque du véhicule',
                'required': True,
            }),
            'imma_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'imma_a',
                'placeholder': 'Immatriculation',
                'required': True,
            }),
            'visite_du_a': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'visite_du_a',
                'placeholder': 'Visite technique du',
                'type': 'date',
                'required': True,
            }),
            'visite_au_a': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'visite_au_a',
                'placeholder': 'Visite technique au',
                'type': 'date',
                'required': True,
            }),
            'usage_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'usage_a',
                'placeholder': 'Usage',
                'required': True,
            }),
            'conducteur_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'conducteur_a',
                'placeholder': 'Nom et Prénoms',
                'required': True,
            }),
            'adresse_conducteur_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'adresse_conducteur_a',
                'placeholder': 'Adresse',
                'required': True,
            }),
            'phone_conducteur_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'phone_conducteur_a',
                'placeholder': 'Téléphone',
                'required': True,
            }),
            'profession_conducteur_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'profession_conducteur_a',
                'placeholder': 'Profession',
                'required': True,
            }),
            'numero_permis': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'numero_permis',
                'placeholder': 'Numéro de permis',
                'required': True,
            }),
            'date_delivrance_a': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'date_delivrance_a',
                'placeholder': 'Date de délivrance',
                'type': 'date',
                'required': True,
            }),
            'lieu_delivrance_a': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'lieu_delivrance_a',
                'placeholder': 'Lieu de délivrance',
                'required': True,
            }),
            'categorie_a': forms.Select(choices=Sinistre.CATEGORIE_CHOICES, attrs={
                'class': 'form-control border-0',
                'id': 'categorie_a',
                'required': True,
            }),
            'dure_a': forms.NumberInput(attrs={
                'class': 'form-control border-0',
                'id': 'dure_a',
                'placeholder': 'Durée de validité (en année)',
                'required': True,
            }),
            'constat_a': forms.RadioSelect(choices=Sinistre.CONSTAT_CHOICES, attrs={
                'class': 'form-check-input',
                'required': True,
            }),
            'salarie_a': forms.RadioSelect(choices=Sinistre.SALARIE_CHOICES, attrs={
                'class': 'form-check-input',
                'required': True,
            }),
            # Partie adverse
            'nom_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'nom_b',
                'placeholder': 'Nom et Prénoms de l\'adversaire',
                'required': True,
            }),
            'adresse_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'adresse_b',
                'placeholder': 'Adresse de l\'adversaire',
                'required': True,
            }),
            'phone_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'phone_b',
                'placeholder': 'Téléphone de l\'adversaire',
                'required': True,
            }),
            'email_b': forms.EmailInput(attrs={
                'class': 'form-control border-0',
                'id': 'email_b',
                'placeholder': 'Email de l\'adversaire',
                'required': True,
            }),
            'marque_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'marque_b',
                'placeholder': 'Marque du véhicule de l\'adversaire',
                'required': True,
            }),
            'imma_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'imma_b',
                'placeholder': 'Immatriculation du véhicule de l\'adversaire',
                'required': True,
            }),
            'visite_du_b': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'visite_du_b',
                'placeholder': 'Visite technique du véhicule de l\'adversaire du',
                'type': 'date',
                'required': True,
            }),
            'visite_au_b': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'visite_au_b',
                'placeholder': 'Visite technique du véhicule de l\'adversaire au',
                'type': 'date',
                'required': True,
            }),
            'usage_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'usage_b',
                'placeholder': 'Usage du véhicule de l\'adversaire',
                'required': True,
            }),
            'conducteur_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'conducteur_b',
                'placeholder': 'Nom et Prénoms du conducteur de l\'adversaire',
                'required': True,
            }),
            'adresse_conducteur_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'adresse_conducteur_b',
                'placeholder': 'Adresse du conducteur de l\'adversaire',
                'required': True,
            }),
            'phone_conducteur_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'phone_conducteur_b',
                'placeholder': 'Téléphone du conducteur de l\'adversaire',
                'required': True,
            }),
            'profession_conducteur_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'profession_conducteur_b',
                'placeholder': 'Profession du conducteur de l\'adversaire',
                'required': True,
            }),
            'numero_permis_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'numero_permis_b',
                'placeholder': 'Numéro de permis du conducteur de l\'adversaire',
                'required': True,
            }),
            'date_delivrance_b': forms.DateInput(attrs={
                'class': 'form-control border-0',
                'id': 'date_delivrance_b',
                'placeholder': 'Date de délivrance du permis du conducteur de l\'adversaire',
                'type': 'date',
                'required': True,
            }),
            'lieu_delivrance_b': forms.TextInput(attrs={
                'class': 'form-control border-0',
                'id': 'lieu_delivrance_b',
                'placeholder': 'Lieu de délivrance du permis du conducteur de l\'adversaire',
                'required': True,
            }),
            'categorie_b': forms.Select(choices=Sinistre.CATEGORIE_CHOICES, attrs={
                'class': 'form-control border-0',
                'id': 'categorie_b',
                'required': True,
            }),
            'dure_b': forms.NumberInput(attrs={
                'class': 'form-control border-0',
                'id': 'dure_b',
                'placeholder': 'Durée de validité du permis du conducteur de l\'adversaire (en année)',
                'required': True,
            }),
            'constat_b': forms.RadioSelect(choices=Sinistre.CONSTAT_CHOICES, attrs={
                'class': 'form-check-input',
                'required': True,
            }),
            'salarie_b': forms.RadioSelect(choices=Sinistre.SALARIE_CHOICES, attrs={
                'class': 'form-check-input',
                'required': True,
            }),

            'circonstance': forms.Textarea(attrs={
                'class': 'form-control border-0',
                'id': 'circonstance',
                'placeholder': 'Décrivez les circonstances de l\'accident, donnez les détails du lieu de l\'accident, directions suivies par les véhicules, ordre des chocs et les points de chocs sur les véhicules, etc.',
                'style': 'height: 200px',
                'required': True,
            }),
            'dommages': forms.Textarea(attrs={
                'class': 'form-control border-0',
                'id': 'dommages',
                'placeholder': "Décrivez les dommages matériels et corporels. Pour les Dommages matériels, veuillez préciser le type de choc (choc lattérale droit, lattérale gauche, avant gauche, avant droit, ...), les matériels endommagés (Pare-brise, feu, ...). Pour les Dommages Corporels, veuillez préciser le nombre de blessés, le nombre de décès, l'intensité des blessures (léger, très léger, grave, très grave), le statut et l'âge des personnes concernées.",
                'style': 'height: 200px',
                'required': True,
            }),
        }

            
        

        