# Generated by Django 5.0.4 on 2024-05-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caroussel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('path', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
