# Generated by Django 5.0.4 on 2024-05-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actualite',
        ),
        migrations.DeleteModel(
            name='Caroussel',
        ),
    ]
