# Generated by Django 5.0.4 on 2024-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroussel',
            name='contenu',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='caroussel',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
