# Generated by Django 5.0.4 on 2024-05-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_caroussel_contenu_alter_caroussel_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='', max_length=150)),
                ('contenu', models.TextField(blank=True, default='')),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('path', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
