# Generated by Django 5.0.4 on 2024-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_delete_actualite_delete_caroussel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='', max_length=150)),
                ('contenu', models.TextField(blank=True, default='')),
                ('date_publication', models.DateField()),
                ('path', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Caroussel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(blank=True, default='')),
                ('path', models.ImageField(upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(blank=True, default='')),
                ('path', models.ImageField(upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
