# Generated by Django 5.0.4 on 2025-08-20 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_categorie_produit_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=150)),
                ('localisation', models.CharField(max_length=150)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='actualite',
            name='contenu',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='titre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administration.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='contenu',
            field=models.TextField(max_length=500),
        ),
    ]
