# Generated by Django 5.0.4 on 2024-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_actualites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualites',
            name='date_publication',
            field=models.DateField(),
        ),
    ]
