# Generated by Django 5.0.4 on 2024-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sinistre', models.DateTimeField(verbose_name='Date et heure du sinistre')),
                ('lieu_sinistre', models.CharField(max_length=255, verbose_name='Lieu exact du sinistre')),
                ('periode_du', models.DateField(verbose_name='Période garantie accordée du')),
                ('periode_au', models.DateField(verbose_name='Période garantie accordée au')),
                ('numero_police', models.BigIntegerField(verbose_name='Numéro de police concerné')),
                ('intervention', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name="Y'a t-il eu intervention de la police ou de la gendarmerie ?")),
                ('nom_a', models.CharField(max_length=255, verbose_name='Nom et Prénoms')),
                ('adresse_a', models.CharField(max_length=255, verbose_name='Adresse')),
                ('phone_a', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_a', models.EmailField(max_length=254, verbose_name='Email')),
                ('marque_a', models.CharField(max_length=100, verbose_name='Marque du véhicule')),
                ('imma_a', models.CharField(max_length=100, verbose_name='Immatriculation')),
                ('visite_du_a', models.DateField(verbose_name='Visite technique du')),
                ('visite_au_a', models.DateField(verbose_name='Visite technique au')),
                ('usage_a', models.CharField(max_length=100, verbose_name='Usage')),
                ('conducteur_a', models.CharField(max_length=255, verbose_name='Nom et Prénoms')),
                ('adresse_conducteur_a', models.CharField(max_length=255, verbose_name='Adresse')),
                ('phone_conducteur_a', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('profession_conducteur_a', models.CharField(max_length=100, verbose_name='Profession')),
                ('numero_permis', models.CharField(max_length=50, verbose_name='Numéro de permis')),
                ('date_delivrance_a', models.DateField(verbose_name='Date de délivrance')),
                ('lieu_delivrance_a', models.CharField(max_length=100, verbose_name='Lieu de délivrance')),
                ('categorie_a', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('ABCDE', 'ABCDE'), ('BCDE', 'BCDE'), ('BDE', 'BDE')], max_length=6, verbose_name='Catégorie du permis')),
                ('dure_a', models.PositiveIntegerField(verbose_name='Durée de validité (en année)')),
                ('constat_a', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name='Constat Amiable ?')),
                ('salarie_a', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name="Est-il salarié de l'assuré ?")),
                ('nom_b', models.CharField(max_length=255, verbose_name="Nom et Prénoms de l'adversaire")),
                ('adresse_b', models.CharField(max_length=255, verbose_name="Adresse de l'adversaire")),
                ('phone_b', models.CharField(max_length=20, verbose_name="Téléphone de l'adversaire")),
                ('email_b', models.EmailField(max_length=254, verbose_name="Email de l'adversaire")),
                ('marque_b', models.CharField(max_length=100, verbose_name="Marque du véhicule de l'adversaire")),
                ('imma_b', models.CharField(max_length=100, verbose_name="Immatriculation du véhicule de l'adversaire")),
                ('visite_du_b', models.DateField(verbose_name="Visite technique du véhicule de l'adversaire du")),
                ('visite_au_b', models.DateField(verbose_name="Visite technique du véhicule de l'adversaire au")),
                ('usage_b', models.CharField(max_length=100, verbose_name="Usage du véhicule de l'adversaire")),
                ('conducteur_b', models.CharField(max_length=255, verbose_name="Nom et Prénoms du conducteur de l'adversaire")),
                ('adresse_conducteur_b', models.CharField(max_length=255, verbose_name="Adresse du conducteur de l'adversaire")),
                ('phone_conducteur_b', models.CharField(max_length=20, verbose_name="Téléphone du conducteur de l'adversaire")),
                ('profession_conducteur_b', models.CharField(max_length=100, verbose_name="Profession du conducteur de l'adversaire")),
                ('numero_permis_b', models.CharField(max_length=50, verbose_name="Numéro de permis du conducteur de l'adversaire")),
                ('date_delivrance_b', models.DateField(verbose_name="Date de délivrance du permis du conducteur de l'adversaire")),
                ('lieu_delivrance_b', models.CharField(max_length=100, verbose_name="Lieu de délivrance du permis du conducteur de l'adversaire")),
                ('categorie_b', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('ABCDE', 'ABCDE'), ('BCDE', 'BCDE'), ('BDE', 'BDE')], max_length=6, verbose_name="Catégorie du permis du conducteur de l'adversaire")),
                ('dure_b', models.PositiveIntegerField(verbose_name="Durée de validité du permis du conducteur de l'adversaire (en année)")),
                ('constat_b', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name="Constat Amiable pour l'adversaire ?")),
                ('salarie_b', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=3, verbose_name="Le conducteur de l'adversaire est-il salarié ?")),
                ('circonstance', models.TextField(help_text="Détails du lieu de l'accident, directions suivies par les véhicules, ordre des chocs et les points de chocs sur les véhicules, etc.", verbose_name='Circonstances')),
                ('dommages', models.TextField(help_text="Détails sur les dommages matériels et corporels. Pour les Dommages matériels, veuillez préciser le type de choc (choc lattérale droit, lattérale gauche, avant gauche, avant droit, ...), les matériels endommagés (Pare-brise, feu, ...). Pour les Dommages Corporels, veuillez préciser le nombre de blessés, le nombre de décès, l'intensité des blessures (léger, très léger, grave, très grave), le statut et l'âge des personnes concernées.", verbose_name='Dommages')),
            ],
        ),
    ]
