# Generated by Django 5.0.4 on 2025-08-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_temoignage_alter_actualite_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visible ?'),
        ),
    ]
