# Generated by Django 5.0.4 on 2024-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='img/')),
                ('titre', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('localisation', models.URLField()),
                ('zone', models.CharField(choices=[('ABIDJAN', 'ABIDJAN'), ('INTERIEUR', 'INTERIEUR')], default='ABIDJAN', max_length=50, verbose_name="Quel est la zone de l'agence ?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AgentGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('localite', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
