# Generated by Django 5.0.4 on 2025-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_produit_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroussel',
            name='lien',
            field=models.URLField(default='http://127.0.0.1:8000/', max_length=300, verbose_name='Lien associé'),
        ),
    ]
