# Generated by Django 5.0.4 on 2024-08-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_sinistre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='adresse_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='adresse_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='adresse_conducteur_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='adresse_conducteur_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='categorie_b',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('ABCDE', 'ABCDE'), ('BCDE', 'BCDE'), ('BDE', 'BDE')], max_length=6, null=True, verbose_name="Catégorie du permis du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='conducteur_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom et Prénoms du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='date_delivrance_b',
            field=models.DateField(blank=True, null=True, verbose_name="Date de délivrance du permis du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='dure_b',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Durée de validité du permis du conducteur de l'adversaire (en année)"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='email_a',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='email_b',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='imma_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Immatriculation du véhicule de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='lieu_delivrance_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu de délivrance du permis du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='marque_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Marque du véhicule de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='nom_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom et Prénoms de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='numero_permis_b',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro de permis du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='phone_b',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='phone_conducteur_a',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='phone_conducteur_b',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='profession_conducteur_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='profession_conducteur_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Profession du conducteur de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='usage_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Usage du véhicule de l'adversaire"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='visite_au_b',
            field=models.DateField(blank=True, null=True, verbose_name="Visite technique du véhicule de l'adversaire au"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='visite_du_b',
            field=models.DateField(blank=True, null=True, verbose_name="Visite technique du véhicule de l'adversaire du"),
        ),
    ]
