# Generated by Django 5.0.4 on 2024-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_actualites_date_publication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actualites',
            new_name='Actualite',
        ),
    ]
