# Generated by Django 5.0.4 on 2024-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_actualites_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroussel',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
