# Generated by Django 5.0.4 on 2025-08-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_caroussel_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, max_length=700, null=True)),
                ('path', models.ImageField(blank=True, default=True, upload_to='img/')),
                ('qui', models.TextField(blank=True, max_length=1000, null=True)),
                ('pourquoi', models.TextField(blank=True, max_length=1000, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('que_faire', models.TextField(blank=True, max_length=1000, null=True)),
                ('autre', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administration.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administration.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administration.produit')),
            ],
        ),
    ]
