# Generated by Django 5.0.4 on 2024-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_sinistre_adresse_a_alter_sinistre_adresse_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='img/')),
                ('titre', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('localisation', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='adresse_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Assuré'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='adresse_conducteur_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='categorie_a',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('ABCDE', 'ABCDE'), ('BCDE', 'BCDE'), ('BDE', 'BDE')], max_length=6, verbose_name='Catégorie du permis  Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='conducteur_a',
            field=models.CharField(max_length=255, verbose_name='Nom et Prénoms Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='date_delivrance_a',
            field=models.DateField(verbose_name='Date de délivrance Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='dure_a',
            field=models.PositiveIntegerField(verbose_name='Durée de validité (en année)  Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='imma_a',
            field=models.CharField(max_length=100, verbose_name='Immatriculation Assuré'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='lieu_delivrance_a',
            field=models.CharField(max_length=100, verbose_name='Lieu de délivrance Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='marque_a',
            field=models.CharField(max_length=100, verbose_name='Marque du véhicule Assuré'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='nom_a',
            field=models.CharField(max_length=255, verbose_name='Nom et Prénoms Assuré'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='numero_permis',
            field=models.CharField(max_length=50, verbose_name='Numéro de permis Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='phone_a',
            field=models.CharField(max_length=20, verbose_name='Téléphone Assuré'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='phone_conducteur_a',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='profession_conducteur_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession Conducteur'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='usage_a',
            field=models.CharField(max_length=100, verbose_name='Usage Assuré'),
        ),
    ]
