# Generated by Django 5.0.4 on 2024-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_agence_alter_sinistre_adresse_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='zone',
            field=models.CharField(choices=[('ABIDJAN', 'ABIDJAN'), ('INTERIEUR', 'INTERIEUR')], default='ABIDJAN', max_length=50, verbose_name="Quel est la zone de l'agence ?"),
        ),
    ]
