# Generated by Django 5.0.4 on 2024-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_caroussel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroussel',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='caroussel',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
