# Generated by Django 5.0.4 on 2025-08-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_detailproduit_formule_garantie'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantie',
            name='formule',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.formule'),
        ),
    ]
