# Generated by Django 5.0.4 on 2025-08-27 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_garantie_formule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.produit'),
        ),
        migrations.AlterField(
            model_name='formule',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formule',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.produit'),
        ),
        migrations.AlterField(
            model_name='garantie',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='garantie',
            name='formule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.formule'),
        ),
        migrations.AlterField(
            model_name='garantie',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.produit'),
        ),
    ]
