# Generated by Django 5.0.4 on 2024-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_caroussel_slug_alter_caroussel_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caroussel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='caroussel',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
