# Generated by Django 5.0.4 on 2025-08-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_detailproduit_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantie',
            name='formule',
        ),
    ]
