# Generated by Django 5.0.4 on 2024-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_remove_caroussel_slug_alter_caroussel_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='caroussel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caroussel',
            name='creator',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='caroussel',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='caroussel',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
