# Generated by Django 5.0.4 on 2025-08-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_remove_garantie_formule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproduit',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
