# Generated by Django 5.0.4 on 2024-05-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_caroussel_created_at_caroussel_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(blank=True, default='')),
                ('path', models.ImageField(upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('creator', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
