# Generated by Django 5.0.4 on 2024-05-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caroussel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
