# Generated by Django 5.0.4 on 2025-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_detailproduit_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
