# Generated by Django 5.0.4 on 2025-08-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_produit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slogan',
            field=models.CharField(default='Protection complète pour votre véhicule avec SAAR Assurances', max_length=100),
        ),
    ]
